name: 'monkeModMail'
main: 'online.monkegame.monkemodmail.Main'
version: '1.1'
api-version: '1.17'
author: 'Mrs_Herobrine_'
website: 'github.com/monkegame/monkemodmail'
commands:
  report:
    description: 'reports a player'
    usage: '/report <player> <reason>'
    permission: 'monkemodmail.report'
  modmail:
    description: 'mails the mods'
    usage: '/modmail <mail>'
    permission: 'monkemodmail.modmail'
